spring:
  application:
    name: spring-batch
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=PostgreSQL
      username: sa
      password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
